ERROR 2024-09-17 10:12:39,491 log Internal Server Error: /api/courses/2/enroll/
Traceback (most recent call last):
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/abhishek/Documents/cms/Cms/py-env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/abhishek/Documents/cms/Cms/educa/courses/api/views.py", line 36, in post
    logger.info(
NameError: name 'logger' is not defined
